name: php-unit-tests

# I am limiting the branches on which this workflow is run for a push so we
# don't run it multiple times when pushing fixes to comments on a PR. In
# principle we don't do pushes except to feature branches but there have been a
# few times we cherry picked onto a release and it's just a good idea to protect
# the main/master and develop branches in case of an accidental commit.
on:
    push:
        branches:
            - "main"
            - "develop"
            - "releases/**"
    pull_request:

jobs:
    run-php-unit-tests:
        name: Run PHP Unit Tests
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Cache Composer dependencies
              uses: actions/cache@v3
              with:
                  path: /tmp/composer-cache
                  key: ${{ runner.os }}-${{ hashFiles('**/composer.lock') }}

            - uses: php-actions/composer@v6

            - uses: php-actions/phpunit@v3
              with:
                  php_version: "8.0"
                  version: "9"
                  configuration: ./phpunit.xml
                  memory_limit: 256M
                  testsuite: ci
