# Validate checked-in code using PHPCS

name: action-php-codesniffer

# Controls when the workflow will run
on:
    push:
        branches:
            - "master"
            - "develop"
            - "releases/**"
    pull_request:

    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
    phpcs:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: php-actions/composer@v6

            - name: PHP Code Sniffer
              uses: php-actions/phpcs@v1
              with:
                  path: ./
                  standard: phpcs.xml
