# Validate checked-in code using PHPCS

name: action-php-codesniffer

# Controls when the workflow will run
on:
    push:
        branches:
            - "master"
            - "develop"
            - "releases/**"
    pull_request:

    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

jobs:
    phpcs:
        name: Check PHP Code Style
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Cache Composer dependencies
              uses: actions/cache@v3
              with:
                  path: /tmp/composer-cache
                  key: ${{ runner.os }}-${{ hashFiles('**/composer.lock') }}

            - uses: php-actions/composer@v6

            - uses: tinovyatkin/action-php-codesniffer@v1
              with:
                  files: "**.php"
                  phpcs_path: php vendor/bin/phpcs
                  standard: phpcs.xml
